### ISSUE TITLE
Waiting for socket server

### ISSUE THREAD

**Issue by ftrotin** [okanulas/Pathfind3r#2] opened 2016-11-25 13:22 UTC
Hello,

The Pathfinder web page logs this after installation:
`> ERROR:`
`> OPENED:`
`> ERROR:`
`> OPENED:`
`> Waiting for socket server`
`> Welcome to Lego Pathfinder`

Here are the steps I did:
- Download and flash ev3dev-jessie-ev3-generic-2016-10-17.img on sdcard with Etcher
- Boot sdcard with USB connexion to my PC
- Setup USB connexion on my Linux PC
- Setup USB connexion on EV3
- `ssh robot@10.42.0.168`
`sudo apt-get update`
`sudo apt-get dist-upgrade`
`sudo reboot`
`sudo apt-get install apache2 php5 libapache2-mod-php5`
`sudo /etc/init.d/apache2 restart`
- check http://10.42.0.168 web page
- `sudo vi /var/www/html/phpinfo.php`
- add `<?php phpinfo(); ?>` to phpinfo.php
- check http://10.42.0.168/phpinfo.php web page
- `sudo git clone https://github.com/okanulas/Pathfind3r.git /var/www/html/Pathfind3r/`
- check http://10.42.0.168/Pathfind3r web page

Am I missing something ?

PS : Sensor and motors are not plugged yet as I don't know which port to use.

**Comment by okanulas** [comment] 2016-11-25 20:08
Hi Fred53,

I'm happy that you're interested in this project. I'll try to help you out.

0. The motors should be connected to the brick to be fully functional. Socket server could fail because there are  motor and sensor checks in the python files. It is easy to remove this check but there could be other problems that prevent the server from starting.

1. There could be a access violation problem which prevents php to run python scripts. First Make sure that the project files can be executed by system by changing the chmod to 777. Change the path if necessary and run the code below:
**chmod -R 777 /var/www/html/Pathfind3r/**  

2. You need to update your sudoers to supresss the password entry when using sudo commands. Open the sudoers file >  "sudo nano /etc/sudoers" .  It should contain the lines below. specially the one starts with www-data. 
```
root    ALL=(ALL:ALL) ALL
robot   ALL=(ALL:ALL) NOPASSWD:ALL
www-data ALL=(ALL) NOPASSWD: ALL

%sudo   ALL=(ALL:ALL) ALL
```


3. We need to check the permissions with a php script. Save below code as test.php and copy to the 
/var/www/html then send me the output. Maybe i can figure out something from the output.

```
<?php
echo "\n-----------------------------\n";
echo shell_exec("whoami");
echo "\n-----------------------------\n";
echo shell_exec("php -v  2>&1");
echo "\n-----------------------------\n";
echo shell_exec("ls -lah 2>&1");
echo "\n-----------------------------\n";
echo shell_exec("pwd 2>&1");
echo "\n-----------------------------\n";
echo shell_exec('sudo python python/socket_server.py 2>&1' );
echo "\n-----------------------------\n";
?>
```

**Comment by ftrotin** [comment] 2016-11-26 10:05
Hi okanulas,
Here are steps done:
`sudo chmod -R 777 /var/www/html/Pathfind3r`
`sudo nano /etc/sudoers`
Added this:
`robot   ALL=(ALL:ALL) NOPASSWD:ALL`
`www-data        ALL=(ALL) NOPASSWD: ALL`

`sudo vi /var/www/html/Parhfind3r/test.php` (rather than in html folder)
Added your code

Here is the output (same output if sensor and motors are connected or not):
`----------------------------- www-data ----------------------------- PHP 5.6.27-0+deb8u1 (cli) (built: Oct 23 2016 13:49:23) Copyright (c) 1997-2016 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies ----------------------------- total 72K drwxrwxrwx 7 root root 4.0K Nov 26 09:51 . drwxr-xr-x 3 root root 4.0K Nov 26 09:40 .. drwxrwxrwx 8 root root 4.0K Nov 24 21:20 .git -rwxrwxrwx 1 root root 1.1K Nov 24 21:20 LICENSE -rwxrwxrwx 1 root root 1.5K Nov 24 21:20 README.md drwxrwxrwx 2 root root 4.0K Nov 24 21:20 css drwxrwxrwx 2 root root 4.0K Nov 24 21:20 images -rwxrwxrwx 1 root root 11K Nov 24 21:20 index.php drwxrwxrwx 3 root root 4.0K Nov 24 21:20 js drwxrwxrwx 2 root root 4.0K Nov 26 09:41 python -rwxrwxrwx 1 root root 1.9K Nov 24 21:20 python_console.php -rwxrwxrwx 1 root root 2.6K Nov 24 21:20 python_controller.php -rwxrwxrwx 1 root root 2.3K Nov 24 21:20 python_socket_server.php -rwxrwxrwx 1 root root 2.7K Nov 24 21:20 svg_draw.php -rw-r--r-- 1 root root 445 Nov 26 09:52 test.php -rwxrwxrwx 1 root root 1.6K Nov 24 21:20 upload.php ----------------------------- /var/www/html/Pathfind3r ----------------------------- Traceback (most recent call last): File "python/socket_server.py", line 39, in lego_printer = LegoPrinter() File "/var/www/html/Pathfind3r/python/printer.py", line 43, in __init__ self.touch_sensor = TouchSensor() File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 1664, in __init__ Device.__init__(self, self.SYSTEM_CLASS_NAME, name_pattern, name_exact, driver_name=['lego-ev3-touch', 'lego-nxt-touch'], **kwargs) File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 180, in __init__ name = next(list_device_names(classpath, name_pattern, **kwargs)) File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 123, in list_device_names for f in os.listdir(class_path): OSError: [Errno 2] No such file or directory: '/sys/class/lego-sensor' -----------------------------`
Which port (1-4,A-D) has to be used for each sensor/motor ?

**Comment by okanulas** [comment] 2016-11-26 18:58
Ok, everything seems alright. You should plug the motors and touch sensor at the right sockets now. Calibrate system before drawing otherwise rail motor could try to go beyond the rail.

A -> The rail motor
B -> Paper feed motor
C -> Pen motor
1 -> Touch sensor

**Comment by ftrotin** [comment] 2016-11-27 12:25
Sensor et motors are plugged but motors don't move.
I tried to see when python script is running at different steps:
After boot:
`robot@ev3dev:~$ ps aux | grep py`
`robot      567  5.0  2.2   2620  1308 pts/0    S+   12:10   0:00 grep py`
After displaying http://10.42.0.168/Pathfinder:
`robot@ev3dev:~$ ps aux | grep py`
`robot      574  0.0  2.4   2620  1436 pts/0    S+   12:14   0:00 grep py`
After clicking on `Start server` (`Service started` hearded):
`robot@ev3dev:~$ ps aux | grep py`
`www-data   575  0.1  1.8   1848  1084 ?        S    12:17   0:00 sh -c sudo python ./python/socket_server.py`
`root       576  1.3  4.5   5180  2676 ?        S    12:17   0:00 sudo python ./python/socket_server.py`
`root       580 23.1 17.1  23044 10048 ?        Sl   12:17   0:03 python ./python/socket_server.py`
`robot      590  0.0  2.2   2620  1312 pts/0    S+   12:17   0:00 grep py`
After clicking on `Calibrate` (`Calibrating motor positions` hearded):
`robot@ev3dev:~$ ps aux | grep py`
`www-data   575  0.0  1.8   1848  1084 ?        S    12:17   0:00 sh -c sudo python ./python/socket_server.py`
`root       576  0.1  4.4   5180  2596 ?        S    12:17   0:00 sudo python ./python/socket_server.py`
`root       580 29.0 17.3  32260 10148 ?        Sl   12:17   0:56 python ./python/socket_server.py`
`robot      599  0.0  2.4   2620  1460 pts/0    S+   12:20   0:00 grep py`
Then nothing happens (`> ERROR:` and `> OPENED:` are still displaying).

**Comment by okanulas** [comment] 2016-11-27 12:56
Could you run the test.php and send me the output?

**Comment by ftrotin** [comment] 2016-11-27 15:37
When launched from webpage, `Service started` hearded but nothing display.
If webpage refreshed, here is the output:
`----------------------------- www-data ----------------------------- PHP 5.6.27-0+deb8u1 (cli) (built: Oct 23 2016 13:49:23) Copyright (c) 1997-2016 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies ----------------------------- total 72K drwxrwxrwx 7 root root 4.0K Nov 26 09:51 . drwxr-xr-x 3 root root 4.0K Nov 26 09:40 .. drwxrwxrwx 8 root root 4.0K Nov 24 21:20 .git -rwxrwxrwx 1 root root 1.1K Nov 24 21:20 LICENSE -rwxrwxrwx 1 root root 1.5K Nov 24 21:20 README.md drwxrwxrwx 2 root root 4.0K Nov 24 21:20 css drwxrwxrwx 2 root root 4.0K Nov 24 21:20 images -rwxrwxrwx 1 root root 11K Nov 24 21:20 index.php drwxrwxrwx 3 root root 4.0K Nov 24 21:20 js drwxrwxrwx 2 root root 4.0K Nov 26 09:41 python -rwxrwxrwx 1 root root 1.9K Nov 24 21:20 python_console.php -rwxrwxrwx 1 root root 2.6K Nov 24 21:20 python_controller.php -rwxrwxrwx 1 root root 2.3K Nov 24 21:20 python_socket_server.php -rwxrwxrwx 1 root root 2.7K Nov 24 21:20 svg_draw.php -rw-r--r-- 1 root root 445 Nov 26 09:52 test.php -rwxrwxrwx 1 root root 1.6K Nov 24 21:20 upload.php ----------------------------- /var/www/html/Pathfind3r ----------------------------- Traceback (most recent call last): File "python/socket_server.py", line 45, in socket.bind((host, port)) File "/usr/lib/python2.7/socket.py", line 224, in meth return getattr(self._sock,name)(*args) socket.error: [Errno 98] Address already in use -----------------------------`

**Comment by okanulas** [comment] 2016-11-27 16:45
The problem is the socket server is already in use.  There is no close socket server button in the web interface ( I should add it) so you need to do it at the terminal. 

1-> Kill all python processes. > sudo killall -9 python
2-> It takes some time to kill the process. You can check the active python processes. >  ps -elf | grep python
3 -> Start the server again using web interface. Just be sure to click start server button only once and wait for the "Server Started"  sound. Then everything should work just fine.

**Comment by ftrotin** [comment] 2016-11-27 17:19
This doesn't change the result.

I tried this
`sudo killall -9 python`
http://10.42.0.168/Pathfind3r/test.php displayed (`Server Started` sound) but no output (webpage keeps loading)
http://10.42.0.168/Pathfind3r displayed (No error, logs > `1--> received:receive` and `> OPENED:`)
Click on `Calibrate` (`Calibrating motor positions` sound) but nothing happens after that.

And this:
`sudo killall -9 python`
http://10.42.0.168/Pathfind3r displayed and click on `Start server` (No error, logs > `1--> received:receive` and `> OPENED:`)
Click on `Display Status` (`> 2--> received:get_info{"rail_motor": {"connected": "false"}, "touch_sensor": {"connected": "true", "mode": "TOUCH", "value": 0, "address": "in1"}, "pen_motor": {"connected": "false"}, "paper_motor": {"connected": "false"}}`)
Click on `Calibrate` (`Calibrating motor positions` sound) but nothing happens after that.

**Comment by okanulas** [comment] 2016-11-27 18:55
1. sudo killall -9 python
2. Open page at http://10.42.0.168/Pathfind3r
3. Start Server
These steps are correct. I see that the motors doesnt seem to be connected at the status message, only touch sensor is connected. Could you check your motor connections again?

**Comment by ftrotin** [comment] 2016-11-27 19:33
Connexions checked (cable inverted between motor and sensor) and only sensor is `connected:true` in `Display Status`.
In `Device Browser` of the EV3 brick, motors are connected (values can be seen when moving motors manually):
- tacho-motor motor9: outA
- tacho-motor motor8: outB
- tacho-motor motor6: outC

**Comment by okanulas** [comment] 2016-11-27 21:29
I think the problem is about the motors. In my setup i got the following output when displaying the status:

```{"rail_motor":` {"polarity": "normal", "connected": "true", "duty_cyle": 0, "position": 0, "stop_command": "coast", "address": "outA"}, "touch_sensor": {"connected": "true", "mode": "TOUCH", "value": 0, "address": "in4"}, "pen_motor": {"polarity": "inversed", "connected": "true", "duty_cyle": 0, "position": 172, "stop_command": "hold", "address": "outB"}, "paper_motor": {"polarity": "inversed", "connected": "true", "duty_cyle": 0, "position": 172, "stop_command": "hold", "address": "outB"}}```

I'm using LargeMotor Class, maybe your motors are compatible with other motor types. To determine your motor types we need to make some manual debugging.

1. Open terminal. Connect to the brick and write "python" then Enter
2. It should display something like 
`Python 2.7.9 (default, Mar  1 2015, 13:52:09) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.`


3. `from ev3dev.auto import *`
4. Now we'll try to understand which motor class we should select. Use the output of the paper feed motor as parameter. I used OUTPUT_B
`m = LargeMotor(OUTPUT_B)`
if you got an error here that means your motor is not a Large motor. Keep trying below command until there is no error message
`m = Motor(OUTPUT_B)`
`m = MediumMotor(OUTPUT_B)`
`m = DcMotor(OUTPUT_B)`
`m = ServoMotor(OUTPUT_B)`
5. If one of the above command works successfully try below commands to rotate the motor.
`m.run_to_abs_pos(position_sp=100, duty_cycle_sp=50) `
`m.run_to_abs_pos(position_sp=200, duty_cycle_sp=50) `

**Comment by ftrotin** [comment] 2016-11-28 12:16
`m = LargeMotor(OUTPUT_B)` gives no error
`m.run_to_abs_pos(position_sp100, duty_cycle_sp=50)` gives nothing (no output, no motor move)

`m = Motor(OUTPUT_B)` gives no error
`m.run_to_abs_pos(position_sp100, duty_cycle_sp=50)` gives nothing (no output, no motor move)

`m = MediumMotor(OUTPUT_B)` gives no error
`m.run_to_abs_pos(position_sp100, duty_cycle_sp=50)` gives this error:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 694, in run_to_abs_pos`
`    setattr(self, key, kwargs[key])`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 359, in duty_cycle_sp`
`    self.set_attr_int('duty_cycle_sp', value)`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 210, in set_attr_int`
`    self._set_attribute(attribute, '{0:d}'.format(int(value)))`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 204, in _set_attribute`
`    self._attribute_cache.write(abspath(self._path + '/' + attribute), value)`
`AttributeError: 'MediumMotor' object has no attribute '_path'`

`m = DcMotor(OUTPUT_B)` gives no error
`m.run_to_abs_pos(position_sp100, duty_cycle_sp=50)` gives this error:
`Exception AttributeError: "'MediumMotor' object has no attribute '_path'" in <bound method`
`MediumMotor.__del__ of <ev3dev.core.MediumMotor object at 0xb6b7d7b0>> ignored`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`AttributeError: 'DcMotor' object has no attribute 'run_to_abs_pos'`

`m = ServoMotor(OUTPUT_B)` gives this error:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 1050, in __init__`
`    Device.__init__(self, self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 180, in __init__`
`    name = next(list_device_names(classpath, name_pattern, **kwargs))`
`  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 123, in list_device_names`
`    for f in os.listdir(class_path):`
`OSError: [Errno 2] No such file or directory: '/sys/class/servo-motor'`

**Comment by okanulas** [comment] 2016-11-28 15:42
There is a little typo at your command. it should be position_sp =100. And you need to run both commands for the motor. First one changes the motor position to 100 other is set to 200. 
Could you try running the following python code?

```
from ev3dev.auto import *
m1 = LargeMotor(OUTPUT_B)
m1.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
m1.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)

m2 = LargeMotor(OUTPUT_A)
m2.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
m2.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)

m3 = LargeMotor(OUTPUT_C)
m3.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
m3.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)
```

**Comment by ftrotin** [comment] 2016-11-28 19:03
Motors don't move and here is the result of your commands:

```
robot@ev3dev:~$ python
Python 2.7.9 (default, Aug 13 2016, 17:33:18) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ev3dev.auto import *
>>> m1 = LargeMotor(OUTPUT_B)
>>> m1.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
>>> m1.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)
>>> m2 = LargeMotor(OUTPUT_A)
>>> m2.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
>>> m2.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)
>>> m3 = LargeMotor(OUTPUT_C)
>>> m3.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 694, in run_to_abs_pos
    setattr(self, key, kwargs[key])
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 359, in duty_cycle_sp
    self.set_attr_int('duty_cycle_sp', value)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 210, in set_attr_int
    self._set_attribute(attribute, '{0:d}'.format(int(value)))
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 204, in _set_attribute
    self._attribute_cache.write(abspath(self._path + '/' + attribute), value)
AttributeError: 'LargeMotor' object has no attribute '_path'
>>> m3.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 694, in run_to_abs_pos
    setattr(self, key, kwargs[key])
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 359, in duty_cycle_sp
    self.set_attr_int('duty_cycle_sp', value)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 210, in set_attr_int
    self._set_attribute(attribute, '{0:d}'.format(int(value)))
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 204, in _set_attribute
    self._attribute_cache.write(abspath(self._path + '/' + attribute), value)
AttributeError: 'LargeMotor' object has no attribute '_path'
>>> 
```

**Comment by okanulas** [comment] 2016-11-28 19:20
It seems like the problem is at the 3rd motor. Please try to run m1 and m2 motors only. 


```
from ev3dev.auto import *
m1 = LargeMotor(OUTPUT_B)
m1.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
m1.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)

m2 = LargeMotor(OUTPUT_A)
m2.run_to_abs_pos(position_sp=100, duty_cycle_sp=50)
m2.run_to_abs_pos(position_sp=200, duty_cycle_sp=50)
```

**Comment by ftrotin** [comment] 2016-11-28 19:53
Your commands were run line by line so it does the same if I only run these ones.

**Comment by okanulas** [comment] 2016-11-29 00:13
I've updated my ev3dev dist. to latest version ( i thought it might be version issue). plugged-unplugged motors, switched ports and tried different things to simulate your problem but everything is working fine with my setup. 

Somehow ev3 project cannot access your motors . It is also weird that you can see the motor process at the brick but running python scripts directly on the brick fails. On the other hand your touch sensor seems to be working fine depending on the status display. Unfortunately there is nothing much i can do about making ev3 to recognise your motors because  I dont have  enough information about the ev3dev internals.. You should ask [ev3 team](https://github.com/rhempel/ev3dev-lang-python/issues) for a solution for this issue. Maybe they can figure out something from these outputs. If you can get motors to work, the socket server and web interface should work as well.

Sorry that i couldn't fix your problem.

**Comment by ftrotin** [comment] 2016-11-29 12:19
Third motor is a MediumMotor, as seen in `dmesg`:
```
[   17.840425] tacho-motor motor0: Registered 'lego-ev3-l-motor' on 'outA'.
[   17.862105] tacho-motor motor1: Registered 'lego-ev3-m-motor' on 'outC'.
[   17.891058] tacho-motor motor2: Registered 'lego-ev3-l-motor' on 'outB'.
[   17.942044] lego-sensor sensor0: Registered 'lego-ev3-touch' on 'in1'.
```
So I get no error (but no move) with `MediumMotor` command, like other motors with `LargeMotor` command.

I will ask the ev3 team.

Thank you.

**Comment by okanulas** [comment] 2017-03-11 08:59
Hi Fred53,
It's been a while. I've updated the project to python3. I'm not %100 sure but your motor problem could be resolved with this version.

**Comment by ftrotin** [comment] 2017-03-12 20:25
Thank you for this update.
I can't try it for now but maybe I will test it again some day.

**Closed as completed** 2017-03-12 21:45 UTC
