### ISSUE TITLE
Error occured

### ISSUE THREAD

**Issue by jeune1** [okanulas/Pathfind3r#3] opened 2017-03-09 03:05 UTC
Hello,I've much impressed such a cool project,and 'd like to make the same.

But I have an error as below on the Pathfinder web page.
Please advice to me!!
> ERROR:
> OPENED:

These are the steps I've done.

-Download and flash ev3dev-jessie-ev3-generic-2017-02-11.img on sdcard with Etcher
-Boot sdcard and connecting Wifi with USB-Wifi dongle(WLI-UC-GNME), and connect ssh <IP address>
-Install as below
    sudo apt-get update
    sudo apt-get dist-upgrade
      reboot(operate by EV3 buttons)
    sudo apt-get install apache2 php5 libapache2-mod-php5
    sudo /etc/init.d/apache2 restart
-check http:<IP address> web page
 -sudo vi /var/www/html/phpinfo.php
    add <?php phpinfo(); ?> to phpinfo.php
-check http:<IP address>/phpinfo.php web page
-sudo git clone https://github.com/okanulas/Pathfind3r.git /var/www/html/Pathfind3r/
-check http:<IP address>/Pathfind3r web page
 > ERROR:
 > OPENED:
---
Device connction
A -> The rail motor
B -> none
C -> Pen motor
1 -> Touch sensor

Result of your test.php on Issues #2
-----------------------------
www-data
-----------------------------
PHP 5.6.30-0+deb8u1 (cli) (built: Feb 8 2017 10:31:29) Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies with Zend
OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
-----------------------------
total 72K
drwxr-xr-x 7 root root 4.0K Mar 9 02:24 .
drwxr-xr-x 3 root root 4.0K Mar 9 02:17 ..
drwxr-xr-x 8 root root 4.0K Mar 9 02:17 .git
-rw-r--r-- 1 root root 1.1K Mar 9 02:17 LICENSE
-rw-r--r-- 1 root root 1.5K Mar 9 02:17 README.md
drwxr-xr-x 2 root root 4.0K Mar 9 02:17 css
drwxr-xr-x 2 root root 4.0K Mar 9 02:17 images
-rw-r--r-- 1 root root 11K Mar 9 02:17 index.php
drwxr-xr-x 3 root root 4.0K Mar 9 02:17 js
drwxr-xr-x 2 root root 4.0K Mar 9 02:17 python
-rw-r--r-- 1 root root 1.9K Mar 9 02:17 python_console.php
-rw-r--r-- 1 root root 2.6K Mar 9 02:17 python_controller.php
-rw-r--r-- 1 root root 2.3K Mar 9 02:17 python_socket_server.php
-rw-r--r-- 1 root root 2.7K Mar 9 02:17 svg_draw.php
-rw-r--r-- 1 root root 445 Mar 9 02:24 test.php
-rw-r--r-- 1 root root 1.6K Mar 9 02:17 upload.php
-----------------------------
/var/www/html/Pathfind3r
-----------------------------
Traceback (most recent call last): File "python/socket_server.py", line 31, in from ev3dev.auto import * ImportError: No module named ev3dev.auto

**Comment by okanulas** [comment] 2017-03-09 19:29
Hi Jeune1,
I'm glad that you're interested in my project and i'll be happy to help. 

The problem is with the python libraries. I have writen this project with python 2.x and ev3dev started using python 3.x from 2016-10-17 ev3dev image. I'm updating ev3dev to the latest version right now to see if i can convert this project to python 3. I'll let you know about the process.

**Comment by jeune1** [comment] 2017-03-09 23:18
Hi okanulas,
Thank you for quick reply, and I'll waiting for your lecture.

**Comment by okanulas** [comment] 2017-03-11 08:57
Hi jeune1,
I've updated the project to support python3. I also updated the git page with more detailed installation instructions. Could you update the git to the latest version and try to run again? Everything should be working now. Make sure that you connect the motors to the right outputs.

**Comment by jeune1** [comment] 2017-03-12 07:09
Hi okanulas,
Thank you for quick reply, and I tried your new project according to your instruction.
But unfortunately, condition is still same, indicated the same error occurred as below using test.php.
"Traceback (most recent call last): File "python/socket_server.py", line 31, in from ev3dev.auto import * ImportError: No module named ev3dev.auto"
If I can tell you any debug information, plaese let me know. I'll try again in the meantime.

**Comment by okanulas** [comment] 2017-03-12 14:05
I fixed the issues and pushed to git.  I also added "Permisions" section to the readme file because you must give root permissions to data-www to let php call python scipts. It is fairly a simple process. It should be working now. Please let me know if there are other problems.

**Comment by jeune1** [comment] 2017-03-12 23:55
Thank you for reply.
At the previous comment, I've already changed permission by editing sudores.
I'll confirm it again later because I'm in the remote place and inform you the result.

**Comment by jeune1** [comment] 2017-03-13 11:36
I checked again, and the part of my /etc/sudoers as below.

root ALL=(ALL:ALL) ALL
robot ALL=(ALL:ALL) NOPASSWD:ALL
www-data ALL=(ALL) NOPASSWD:ALL

But indicates the error on the Web browser.
Are there any other check points I forgot?

**Comment by okanulas** [comment] 2017-03-13 11:44
Could you run test.php and send me the results? Also could you try running server manually? 
First you need to navigate to /var/www/html/pathfind3r. Then run the command below.
`sudo python3 python/socket_server.py`
if there is an error like the port is in use run below command and wait for a minute or two. Then try running server manually.
`sudo killall -9 python`

**Comment by jeune1** [comment] 2017-03-13 12:01
The command "sudo python3 python/socket_server.py"runs and sounds "Service is started".
And test.php indicates as below.
----------------------------- www-data ----------------------------- 
PHP 5.6.30-0+deb8u1 (cli) (built: Feb 8 2017 10:31:29) Copyright (c) 1997-2016 The PHP Group 
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies with Zend 
OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies 
----------------------------- 
total 76K drwxrwxrwx 7 root root 4.0K Mar 12 06:42 . 
drwxr-xr-x 3 root root 4.0K Mar 12 06:42 .. 
drwxrwxrwx 8 root root 4.0K Mar 12 06:42 .git 
-rwxrwxrwx 1 root root 1.1K Mar 12 06:42 LICENSE 
-rwxrwxrwx 1 root root 3.4K Mar 12 06:42 README.md 
drwxrwxrwx 2 root root 4.0K Mar 12 06:42 css 
drwxrwxrwx 2 root root 4.0K Mar 12 06:42 images 
-rwxrwxrwx 1 root root 11K Mar 12 06:42 index.php 
-rwxrwxrwx 1 root root 21 Mar 12 06:42 info.php 
drwxrwxrwx 3 root root 4.0K Mar 12 06:42 js 
drwxrwxrwx 3 root root 4.0K Mar 13 11:51 python 
-rwxrwxrwx 1 root root 1.9K Mar 12 06:42 python_console.php 
-rwxrwxrwx 1 root root 2.6K Mar 12 06:42 python_controller.php 
-rwxrwxrwx 1 root root 2.3K Mar 12 06:42 python_socket_server.php 
-rwxrwxrwx 1 root root 2.7K Mar 12 06:42 svg_draw.php 
-rwxrwxrwx 1 root root 444 Mar 12 06:42 test.php 
-rwxrwxrwx 1 root root 1.6K Mar 12 06:42 upload.php 
----------------------------- 
/var/www/html/pathfind3r 
----------------------------- 
Traceback (most recent call last): File "python/socket_server.py", line 31, in from ev3dev.auto import * ImportError: No module named ev3dev.auto 
-----------------------------

**Comment by okanulas** [comment] 2017-03-13 12:16
Could you try running below command at  /var/www/html/pathfind3r
`git reset --hard`
`git pull`
Then run the test.php again.

**Comment by jeune1** [comment] 2017-03-13 12:21
Just Info., After above,pathfinder (FEED, PEN and CALIBRATE) runs!
But only reboot(without command "sudo python3 python/socket_server.py"),pathfinder is not run.
I'll try git operation as your comment, please wait!

**Comment by jeune1** [comment] 2017-03-13 12:43
I operated git, and test.php result is as below.-----------------------------
www-data 
-----------------------------
PHP 5.6.30-0+deb8u1 (cli) (built: Feb 8 2017 10:31:29) Copyright (c) 1997-2016 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies 
-----------------------------
total 72K drwxrwxrwx 7 root root 4.0K Mar 13 12:23 . drwxr-xr-x 3 root root 4.0K Mar 12 06:42 .. drwxrwxrwx 8 root root 4.0K Mar 13 12:23 .git -rw-r--r-- 1 robot robot 1.1K Mar 13 12:22 LICENSE -rw-r--r-- 1 robot robot 3.8K Mar 13 12:23 README.md drwxrwxrwx 2 root root 4.0K Mar 13 12:22 css drwxrwxrwx 2 root root 4.0K Mar 13 12:23 images -rw-r--r-- 1 robot robot 11K Mar 13 12:22 index.php -rw-r--r-- 1 robot robot 21 Mar 13 12:22 info.php drwxrwxrwx 3 root root 4.0K Mar 13 12:22 js drwxrwxrwx 3 root root 4.0K Mar 13 12:23 python -rw-r--r-- 1 robot robot 1.9K Mar 13 12:22 python_console.php -rw-r--r-- 1 robot robot 2.4K Mar 13 12:23 python_socket_server.php -rw-r--r-- 1 robot robot 2.7K Mar 13 12:22 svg_draw.php -rw-r--r-- 1 robot robot 485 Mar 13 12:23 test.php -rw-r--r-- 1 robot robot 1.6K Mar 13 12:22 upload.php 
-----------------------------
/var/www/html/pathfind3r 
-----------------------------
Traceback (most recent call last): File "python/socket_server.py", line 46, in socket.bind((host, port)) OSError: [Errno 98] Address already in use 
-----------------------------

and reboot EV3, the result of test.php is same in last line.
 Traceback (most recent call last): File "python/socket_server.py", line 46, in socket.bind((host, port)) OSError: [Errno 98] Address already in use

**Comment by okanulas** [comment] 2017-03-13 12:48
Everything should be working now. You can try stoping and starting server from web interface.

**Comment by jeune1** [comment] 2017-03-13 12:55
I can draw the maze from Web Interfece!
Thank you so much for your kind correspondence!!

**Comment by okanulas** [comment] 2017-03-13 13:08
I'm glad that we solved the issue. And the project is also upgraded to work with the latest version of Ev3dev. Have a nice day and happy drawings. I'm closing the issue.

**Closed as completed by okanulas** 2017-03-13 13:08 UTC
